### PR TITLE
.existsSync() now lives in the fs module.

### PR DESCRIPTION
**Pull request by cryptix**
Just to get rid of the warnings.

### CODE REVIEW

**Comment by blakmatrix** [comment]
:+1: --odd though how migratorBot over looked this....

**Comment by cryptix** [comment]
There is one more in the deps but I couldn't narrow it down yet.

**Comment by jfhbrook** [comment]
It would be nice if this did something like the following to support both 0.6.x and 0.8.x:

```
var exists = fs.exists? fs.exists : path.exists
```

Otherwise, lgtm.

**Comment by cryptix** [comment]
Agreed. How about this? I hope the inline require() isn't to painful to the eyes.

**Comment by vibegui** [comment]
Why hasn't this been pulled yet? Seems like the project is abandoned.

**Comment by indexzero** [comment]
Closing since `blacksmith` has been rewritten from the ground up for `1.0.0`

**Pull request closed without merging**
