### PR TITLE
Allow defaultAuthor to be defined in config.json

### PR DESCRIPTION
**Pull request by morganrallen**
If defaultAuthor: "derp" and authors/derp.json are both present the specify author prompt with be replaced with

Specify the author (empty to use 'I AM DERP')

Where 'I am DERP' is the value of config.defaultAuthor

### CODE REVIEW

**Comment by jfhbrook** [comment]
Hey @morganrallen,

This looks good! I'll merge it in directly.

**Comment by jfhbrook** [comment]
I don't know why gh didn't auto-detect, but I totally pulled your change in.

**Comment by jfhbrook** [comment]
@morganrallen I reverted this change because it includes  a number of long method chains without any guards against undefineds that was causing problems for some users. If you can add these guards, and do some code cleanup while you're at it (please don't do one line if statements without brackets), I'll consider pulling this back in.

**Comment by pksunkara** [comment]
New implementation is in pr #43

**Pull request closed without merging**
